Repository elastic/kibana-load-testing, pull requests merged in 2022-01, with the labels that each got.

#205 add debug logic, update scenario
  puppeteer/src/index.ts
  puppeteer/src/scenario/demoJourney.ts
Labels: chore

#206 run ingestion when main stage failed
  .ci/Jenkinsfile
  src/test/scala/org/kibanaLoadTest/ingest/Main.scala
Labels: chore

#212 update gatling version to 3.7.3
  pom.xml
  src/test/scala/org/kibanaLoadTest/helpers/HttpHelper.scala
Labels: chore

#216 Add override to cluster uuid
  cfg/metricbeat/metricbeat.yml
Labels: bug-fix

#217 try metal worker
  .ci/Jenkinsfile
Labels: feature, ci
